import { Link } from "@tanstack/react-router";
import { CalendarCheck, LayoutDashboard, Mail, Menu, Search, Sparkles, X } from "lucide-react";
import { useState, type ReactNode } from "react";

export const TOOLS = [
  { to: "/", label: "Dashboard", icon: LayoutDashboard },
  { to: "/email", label: "Email Generator", icon: Mail },
  { to: "/planner", label: "Task Planner", icon: CalendarCheck },
  { to: "/research", label: "Research Assistant", icon: Search },
] as const;

function NavLinks({ onNavigate }: { onNavigate?: () => void }) {
  return (
    <nav className="flex flex-col gap-1">
      {TOOLS.map(({ to, label, icon: Icon }) => (
        <Link
          key={to}
          to={to}
          onClick={onNavigate}
          activeOptions={{ exact: to === "/" }}
          className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-sidebar-foreground transition-colors hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"
          activeProps={{ className: "bg-sidebar-accent text-sidebar-accent-foreground" }}
        >
          <Icon className="size-4" />
          {label}
        </Link>
      ))}
    </nav>
  );
}

function Brand() {
  return (
    <Link to="/" className="flex items-center gap-2.5">
      <span className="gradient-brand grid size-9 place-items-center rounded-xl text-primary-foreground shadow-glow">
        <Sparkles className="size-4" />
      </span>
      <span className="leading-tight">
        <span className="block text-sm font-bold">Workplace AI</span>
        <span className="block text-[11px] text-muted-foreground">Productivity Assistant</span>
      </span>
    </Link>
  );
}

export function AppShell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="bg-page min-h-screen lg:flex">
      <aside className="hidden w-64 shrink-0 border-r border-sidebar-border bg-sidebar lg:sticky lg:top-0 lg:flex lg:h-screen lg:flex-col lg:p-5">
        <Brand />
        <div className="mt-8 flex-1">
          <NavLinks />
        </div>
        <p className="rounded-lg bg-muted p-3 text-[11px] leading-relaxed text-muted-foreground">
          Nothing you type is stored. Everything clears when you refresh or close the tab.
        </p>
      </aside>

      <header className="sticky top-0 z-30 flex items-center justify-between border-b border-sidebar-border bg-sidebar/90 px-4 py-3 backdrop-blur lg:hidden">
        <Brand />
        <button
          type="button"
          aria-label={open ? "Close menu" : "Open menu"}
          onClick={() => setOpen((v) => !v)}
          className="rounded-lg p-2 text-foreground hover:bg-muted"
        >
          {open ? <X className="size-5" /> : <Menu className="size-5" />}
        </button>
      </header>
      {open && (
        <div className="fixed inset-x-0 top-[61px] z-20 border-b border-sidebar-border bg-sidebar p-4 shadow-soft lg:hidden">
          <NavLinks onNavigate={() => setOpen(false)} />
        </div>
      )}

      <main className="min-w-0 flex-1 px-4 py-6 sm:px-6 lg:px-10 lg:py-10">
        <div className="mx-auto max-w-6xl">{children}</div>
        <footer className="mx-auto mt-10 max-w-6xl rounded-xl border border-border bg-card/70 p-4 text-xs leading-relaxed text-muted-foreground">
          <strong className="text-foreground">Responsible AI notice:</strong> Content is generated by AI and may
          contain errors, omissions, or outdated information. Always review and verify before sending, sharing, or
          acting on it.
        </footer>
      </main>
    </div>
  );
}

export function PageHeader({ title, description, icon: Icon }: { title: string; description: string; icon: typeof Mail }) {
  return (
    <div className="mb-6 flex items-start gap-4">
      <span className="grid size-11 shrink-0 place-items-center rounded-xl bg-violet text-violet-foreground">
        <Icon className="size-5" />
      </span>
      <div>
        <h1 className="text-2xl font-bold tracking-tight">{title}</h1>
        <p className="mt-1 text-sm text-muted-foreground">{description}</p>
      </div>
    </div>
  );
}
